project:
  type: website

website:
  title: "Nest"
  navbar:
    title: false
    logo: nest.png
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



