project:
  type: website
  preview:
    browser: true
    port: 5555

website:
  title: "Nest"
  favicon: img/nest.png
  navbar:
    background: light
    title: false
    logo: img/nest.png
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "Products"
        file: products.qmd
      - text: "Gallery"
        file: gallery.qmd
      - text: "Learn"
        file: learn.qmd
      - text: "Events"
        file: events.qmd
      - text: "About Us"
        file: about.qmd

format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 1200px
      margin-width: 200px
      gutter-width: 1.5rem
    theme: cosmo
    mainfont: system-ui
    fontcolor: "#161b58"
    css: styles.css
    toc: false



